### ISSUE TITLE
Pre-build checklist for v0.2.0-RC

### ISSUE THREAD

**Issue by brossi** [Peerunity/Peerunity#105]
Items that need to be completed before v0.2.0-RC is ready:
- [x] [Before v0.2.0 RC build, replace translation files with new ones from GetLocalization](https://github.com/Peerunity/Peerunity/issues/104)
- [x] [Some remaining rebranding string issues](https://github.com/Peerunity/Peerunity/issues/99)
- [x] [Peerunity 0.1.0 client is still reporting as client version "v0.4.0ppc-129-g7cfcf86" - OSX ](https://github.com/Peerunity/Peerunity/issues/82)
- [x] Update versioning information
- [ ] Add new git tag for `v0.2.0-rc`
- [ ] Draft release notes
