### ISSUE TITLE
List of potential pull request mergers (from Bitcoin)

### ISSUE THREAD

**Issue by brossi** [Peerunity/Peerunity#22]
Some of these may already be included, through a separate commit or merger of older code. Will need to confirm before moving forward with any of them, obviously. Most recent (closed) pull requests against Bitcoin-core repo are listed first.
### General
- [ ] [Remove an assignment which is never used. - #3972](https://github.com/bitcoin/bitcoin/pull/3972)
- [ ] [Organize RPCCommands table - #3964](https://github.com/bitcoin/bitcoin/pull/3964)
- [ ] [Remove duplicate from src/makefile.am - #3958](https://github.com/bitcoin/bitcoin/pull/3958)
- [ ] [](https://github.com/bitcoin/bitcoin/pull/)
### OSX-related
- [ ] [Add application category for OSX - #3988](https://github.com/bitcoin/bitcoin/pull/3988)
- [ ] [Build: Allow building for OSX from Linux - #3885](https://github.com/bitcoin/bitcoin/pull/3885)
